version: 0.2

env:
  variables:
    #TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: staff-device-dns-dhcp@justice.gov.uk
    TF_VAR_env: ${ENV}
    TF_VAR_enable_critical_notifications: true
    TF_VAR_enable_authentication: true
    TF_VAR_admin_db_backup_retention_period: 30
    TF_VAR_enable_dhcp_transit_gateway_attachment: true
    TF_VAR_enable_ssh_key_generation: false
    TF_VAR_enable_dhcp_cloudwatch_log_metrics: true
  parameter-store:
    TF_VAR_assume_role: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_pdns_ips: "/staff-device/dns/pdns/ips"
    TF_VAR_pdns_ips_list: "/staff-device/dns/pdns/ips_list"
    TF_VAR_dhcp_db_username: "/codebuild/dhcp/$ENV/db/username"
    TF_VAR_dhcp_db_password: "/codebuild/dhcp/$ENV/db/password"
    TF_VAR_admin_db_username: "/codebuild/dhcp/$ENV/admin/db/username"
    TF_VAR_admin_db_password: "/codebuild/dhcp/$ENV/admin/db/password"
    TF_VAR_azure_federation_metadata_url: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/azure_federation_metadata_url"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_vpn_hosted_zone_id: "/codebuild/$ENV/vpn_hosted_zone_id"
    TF_VAR_vpn_hosted_zone_domain: "/route53/$ENV/vpn_hosted_zone_domain"
    TF_VAR_dhcp_transit_gateway_id: "/staff-device/dhcp/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id: "/staff-device/dhcp/$ENV/transit_gateway_route_table_id"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2a: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2b: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2a: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2b: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dns_route53_resolver_ip_eu_west_2a: "/staff-device/dns/$ENV/dns_route53_resolver_ip_eu_west_2a"
    TF_VAR_dns_route53_resolver_ip_eu_west_2b: "/staff-device/dns/$ENV/dns_route53_resolver_ip_eu_west_2b"
    TF_VAR_admin_sentry_dsn: "/staff-device/admin/sentry_dsn"
    TF_VAR_dns_private_zone: "/staff-device/admin/$ENV/dns_private_zone"
    TF_VAR_dhcp_sentry_dsn: "/staff-device/dhcp/sentry_dsn"
    TF_VAR_dns_sentry_dsn: "/staff-device/dns/sentry_dsn"
    TF_VAR_bastion_allowed_ingress_ip: "/staff-device/corsham_testing/bastion_allowed_ingress_ip"
    TF_VAR_bastion_allowed_egress_ip: "/staff-device/corsham_testing/bastion_allowed_egress_ip"
    TF_VAR_corsham_vm_ip: "/staff-device/corsham_testing/corsham_vm_ip"
    TF_VAR_model_office_vm_ip: "/staff-device/dns-dhcp/model_office_vm_ip"
    TF_VAR_dhcp_egress_transit_gateway_routes: "/staff-device/$ENV/dhcp_egress_transit_gateway_routes"
    TF_VAR_byoip_pool_id: "/staff-device/dns/$ENV/public_ip_pool_id"
    TF_VAR_enable_corsham_test_bastion: "/staff-device/dns-dhcp/$ENV/enable_bastion"
    TF_VAR_allowed_ip_ranges: "/staff-device/dns-dhcp/admin/$ENV/allowed_ip_ranges"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_api_basic_auth_username: "/codebuild/dhcp/admin/api/basic_auth_username"
    TF_VAR_api_basic_auth_password: "/codebuild/dhcp/admin/api/basic_auth_password"
    TF_VAR_shared_services_account_id: "/codebuild/staff_device_shared_services_account_id"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform init -no-color --backend-config="key=terraform.$ENV.state" -reconfigure
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform plan -no-color
      - ./scripts/publish_terraform_outputs.sh
