version: 0.2

env:
  variables:
    #TF_IN_AUTOMATION: true
    TF_INPUT: 0
  parameter-store:
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/1.1.8/terraform_1.1.8_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export TF_VAR_env=${ENV}
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - ./scripts/terraform_plan_or_apply.sh
      - ./scripts/publish_terraform_outputs.sh
